<?php

/*
 * This file is generated by S. Das.
 * Do not copy it without permission.
 */
//Contact at: tapan84silchar[at]gmail.com
include 'config/config.php';
session_start();
unset($_SESSION['user_nm']);
unset($_SESSION['name']);
unset($_SESSION['roll_number']);
unset($_SESSION['class']);
unset($_SESSION['pass_changed']);
unset($_SESSION['last_date']);
header("Location: ".constant("HOST11")."/login.php");
?>
