<!--
This file is generated by S. Das.
Do not copy it without permission.
-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title></title>
    </head>
    <body>
        <?php
        $time_now = mktime(date('H'), date('i'), date('s'),date('m'),date('d'),date('Y'));
        echo date("d-m-Y H:i:s",$time_now);
        ?>
    </body>
</html>
