<?php

/*
 * This file is generated by S. Das.
 * Do not copy it without permission.
 */
//Contact at: tapan84silchar[at]gmail.com
include '../config/config.php';
session_start();
unset($_SESSION['admin_user_nm']);
unset($_SESSION['admin_name']);
unset($_SESSION['role']);

if(isset($_COOKIE['rem_usertype'])) // If the cookie 'Joe2Torials is set, do the following; 
{ 
                            setcookie("rem_usertype", "", -1, '/');
                            setcookie("rem_admin_user_nm", "", -1, '/');
                            setcookie("rem_admin_name", "", -1, '/');
                            setcookie("rem_role", "", -1, '/');
                            
}
//header("Location: ".constant("HOST11")."/Backend/login.php");
header("Location: ".constant("HOST11")."/login.php");
?>
