<?php

/*
 * This file is generated by S. Das.
 * Do not copy it without permission.
 */
//Contact at: tapan84silchar[at]gmail.com
include '../Macros/CommonFunctions.php';
include '../config/config.php';
session_start();
$pageResultString = "";
$finalResult = FALSE;
if (isset($_FILES["fileThesis"])) {
    $title = htmlspecialchars(addslashes($_POST['txtTitle']));
    //$advisor = $_POST['comboAdvisor'];
    //$permission = $_POST['chkPermission'];
    $abstract = htmlspecialchars(addslashes($_POST['txtAbstract']));
    //$thesisFile = $_FILES["fileThesis"];
    $isOverWrite = $_POST['chkOverwrite'];
    $time_now = mktime(date('H') + 5, date('i') + 30, date('s'), date('m'), date('d'), date('Y'));

    $newFileName = $_SESSION['roll_number'] . '-' . $_SESSION['class'] . "PI.pdf";
    if ($title == "" && $abstract == "" && !isInFileFormat($thesisFile["name"], "pdf")) {
        $pageResultString = '<br/><b>Uploading Failed. May be file size is more than 6MB.</b>';
    } else if ($_FILES["fileThesis"]["error"] > 0) {
        $pageResultString = "<br/><br/>File uploading failed. Error: ".codeToMessage($_FILES["fileThesis"]["error"]).".  Please try again.";
    } else if ($_FILES["fileThesis"]["type"] != "application/pdf") {
        $pageResultString = "<br/><br/>File uploading failed. MIME check failed. Regenerate your pdf file and try again.";
    } else if (file_exists("../Upload/" . $_SESSION['class'] . "/" . $newFileName) && $isOverWrite != "ON") {
        $pageResultString = '<br/><b>You already uploaded a report.</b>
            <br/>If you want to overwrite your previous upload, then go to <a href="' . constant("HOST11") . '/upload_thesis.php">uploading page</a> and repeat the process with the <b>overwrite</b> option.';
    } else {
        $result = "NONE";
        if (!($con = mysql_connect(constant("HOSTNAME"), constant("USERNAME"), constant("PASS")))) {
            $result = "DBCONNECTION_ERROR";
        } else if (!($select = mysql_select_db(constant("DBNAME"), $con))) {
            $result = "DBCONNECTION_ERROR";
        } else {
            $sql = "SELECT user_nm FROM projects WHERE user_nm='" . $_SESSION['user_nm'] . "'";
            $rs = mysql_query($sql);
            if (mysql_affected_rows() >= 1) {
                $sql_inner = "UPDATE projects SET thesis_title='" . $title . "',report_file_name='" . $_FILES["fileThesis"]["name"] . "'," .
                        "abstract='" . $abstract . "',submitted_at='" . date("Y-m-d H:i:s", $time_now) . "'," .
                        "submitted_by='" . $_SESSION['name'] . "[" . $_SESSION['user_nm'] . "]' WHERE user_nm='" . $_SESSION['user_nm'] . "'";
            } else {
                $sql_inner = "INSERT INTO projects (user_nm,thesis_title,report_file_name,abstract,submitted_at,submitted_by)" .
                        "VALUES('" . $_SESSION['user_nm'] . "','" . $title . "','" . $_FILES["fileThesis"]["name"] . "'," .
                        "'" . $abstract . "','" . date("Y-m-d H:i:s", $time_now) . "','" . $_SESSION['name'] . "[" . $_SESSION['user_nm'] . "]')";
            }
            $rs = mysql_query($sql_inner);
            //$row = mysql_fetch_assoc($rs);
            if (mysql_affected_rows() >= 1) {
                $result = "DONE";
            } else {
                $result = "UNDONE";
            }
        }
        mysql_close($con);


        if ($result == "DONE") { //If database operation was successful.
            $file_exist = FALSE;
            $file_renamed = FALSE;

            //If file already exists, then rename it to a temp file. The concept of renaming and not deleting is that
            // the new file may not upload successfully. In that case we will loss both the files.
            if (file_exists("../Upload/" . $_SESSION['class'] . "/" . $newFileName)) {
                $file_exist = TRUE;
                //unlink("../Upload/" . $_SESSION['class'] . "/" . $newFileName);
                $file_renamed = rename("../Upload/" . $_SESSION['class'] . "/" . $newFileName, "../Upload/" . $_SESSION['class'] . "/temp_" . $newFileName);
            }

            //If the file was exists but the renaming operation was unsuccessfull.
            if ($file_exist == TRUE && $file_renamed == FALSE) {
                $pageResultString = '<br/><br/><b>Uploading Failed!!!!!!</b><br/>Unable to rename the previously uploaded file. Please try again.';
            } else {
                //Copy the file to exact location.
                $res1 = move_uploaded_file($_FILES["fileThesis"]["tmp_name"], "../Upload/" . $_SESSION['class'] . "/" . $newFileName);

                if ($res1 == FALSE) {
                    $pageResultString = '<br/><br/><b>Uploading Failed!!!!!!</b><br/>Unable to store your file in ../Upload/'.$_SESSION['class'].'/'.$newFileName.'Please try again.';
                } else {
                    unlink("../Upload/" . $_SESSION['class'] . "/temp_" . $newFileName);
                    $log_file_name = $_SESSION["roll_number"] . '-' . date("dMY-G-i-u") . '.pdf';
                    copy("../Upload/" . $_SESSION['class'] . "/" . $newFileName, "../Upload/LOG/" . $_SESSION['class'] . "/" . $log_file_name);
                    $pageResultString = '<br/><br/><b>Uploading Successfull.</b> Error'.codeToMessage($_FILES["fileThesis"]["error"]).'
                                     <br/><br/>Verify the followings by clicking <a href="status.php">here</a>:
                                     <ul>
                                     <li>Make sure that the informations you have entered are all correct.</li>
                                     <li>Download and verify your uploaded thesis file.</li>
                                     </ul>
                                     <b/><br/><span style="color: red;font-weight: bold">Do it now, you cannot complain later.<span/>';
                    $finalResult = TRUE;
                }
            }
        } else { // If data base operation was not successful.
            $pageResultString = '<br/><br/><b>Uploading failed due to some database/file errror.</b>
                                 <br/>Try again by:
                                 <ul>
                                 <li><span style="color: green;font-size: 16px;font-style: italic">Removing all special characters from thesis title and abstract.</span></li>
                                 <li><span style="color: green;font-size: 16px;font-style: italic">Rename your thesis file with a simple and short name. e.g., MyThesis.pdf</span></li>
                                 <li><span style="color: green;font-size: 16px;font-style: italic">Your file wont be upload if its size is grater than 6MB</span></li>
                                 </ul>';
        }
    }
    //******** REMOVE PERMISSION IF UPLOADING SUCCESSFULL***************************
    if ($finalResult == TRUE) {
        $result = "NONE";
        if (!($con = mysql_connect(constant("HOSTNAME"), constant("USERNAME"), constant("PASS")))) {
            $result = "DBCONNECTION_ERROR";
        } else if (!($select = mysql_select_db(constant("DBNAME"), $con))) {
            $result = "DBCONNECTION_ERROR";
        } else {
            $sql_inner = 'UPDATE student set `permission`="NO" where user_nm="' . $_SESSION["user_nm"] . '"';
            mysql_query($sql_inner);
            if (mysql_affected_rows() >= 1) {
                $_SESSION["permission"] = "NO";
            }
        }
        mysql_close($con);
    }
    $_SESSION['queryString'] = $pageResultString;
	//echo getcwd();	
	if (!file_exists('../Upload/'.$_SESSION['class'].'/Report/'.$_SESSION['roll_number'].'-'.$_SESSION['class']."PI")) {
		mkdir('../Upload/'.$_SESSION['class'].'/Report/'.$_SESSION['roll_number'].'-'.$_SESSION['class']."PI", 0777, true);
	}
	chdir('..');
	chdir('Upload');
	chdir($_SESSION['class']);
	//chdir('C:\xampp\htdocs\ProjectUploader\Upload\BT');
	set_time_limit(300);
	//echo getcwd();
	foreach (glob("*.pdf") as $file) {echo $file;
		if($file!=$newFileName){
			echo $file;
			$cmd='"C:\Program Files (x86)\Softinterface, Inc\DiffDoc\DiffDoc"  /M '.getcwd().'\\'.$newFileName.' /S '.getcwd().'\\'.$file.' /I /W /E /B /T '.getcwd().'\Report\\'.$_SESSION['roll_number'].'-'.$_SESSION['class'].'PI\\'.substr($file,0,-4).'.HTM /L '.getcwd().'\Report\\'.$_SESSION['roll_number'].'-'.$_SESSION['class'].'PI\\'.substr($file,0,-4).'.LOG /X';
			echo $cmd;
			echo "<br><br>";
			echo shell_exec($cmd);
		}
	}
	
	$_SESSION['reportFolderName'] = substr($newFileName,0,-4);
	header("Location: " . constant("HOST11") . "/FormProcessor/test.php");
	//generateSummary(substr($newFileName,0,-4));
    //header("Location: " . constant("HOST11") . "/user_result.php");
}
?>
