<?php

/*
 * This file is generated by S. Das.
 * Do not copy it without permission.
 */
//Contact at: tapan84silchar[at]gmail.com
include '../../../../config/config.php';

//Forward to login page if not authenticated.
session_start();
if (!isset($_SESSION['admin_user_nm'])) {
    header("Location: " . constant("HOST11") . "/Backend/login.php");
}


$roll = $_POST['txtClass'];
$last_date = $_POST['txtDate'];
session_start();
if (isset($_POST['txtClass'])) {
    if (!($con = mysql_connect(constant("HOSTNAME"), constant("USERNAME"), constant("PASS")))) {
        $result = "DBCONNECTION_ERROR";
    } else if (!($select = mysql_select_db(constant("DBNAME"), $con))) {
        $result = "DBCONNECTION_ERROR";
    } else {
        $dateParts = explode("/", $last_date);
        $mysqlDate = $dateParts[2] . '-' . $dateParts[1] . '-' . $dateParts[0];
        $sql = "Update schedule SET last_date='$mysqlDate' WHERE class='$roll'";
        mysql_query($sql);
        //$row = mysql_fetch_assoc($result);
        if (mysql_affected_rows() >= 1) {
            $_SESSION['queryResult'] = "Edition Successfull!!. <br/>Go to the <b>Schedule List</b> to see the updates";
            header("Location: " . constant("HOST11") . "/Backend/Schedule/schedule_result.php");
        } else {
            $_SESSION['queryResult'] = "Edition Failed. <br/>Go to the <b>Schedule List</b> and try again.";
            header("Location: " . constant("HOST11") . "/Backend/Schedule/schedule_result.php");
        }
    }
    mysql_close($con);
} else {
    $_SESSION['queryResult'] = "Edition not possible. Some error occured. <br/>Go to the <b>Schedule List</b> to see the updates";
    header("Location: " . constant("HOST11") . "/Backend/Schedule/schedule_result.php");
}
?>
