<?php

/*
 * This file is generated by S. Das.
 * Do not copy it without permission.
 */
//Contact at: tapan84silchar[at]gmail.com
require '../../Database/AdminStudentManager.php';
require '../../../PhpIncludeFiles/CommonFunctions.php';
require '../../../../config/config.php';

//Forward to login page if not authenticated.
session_start();
if (!isset($_SESSION['admin_user_nm'])) {
    header("Location: " . constant("HOST11") . "/Backend/login.php");
}

$resultString="";
if(isInFileFormat($_FILES["fileCSV"]["name"], "csv")){
    $file=$_FILES["fileCSV"];
    $result=processStudentCSVFile($file);
    if($result=="DONE"){
        $resultString="Insertion completed successfully!!!!!!";
    }else if($result=="PARTIAL"){
        $resultString="Insertion done partially.<br/>".$_SESSION['message'];
    }else if($result=="UNDONE"){
        $resultString="Insertion failed completely.<br/>".$_SESSION['message'];;
    }else if($result=="FORMAT_ERROR"){
        $resultString="Insertion failed completely. No valid data found. Check file format.";
    }else if($result=="DBCONNECTION_ERROR"){
        $resultString="Insertion failed. Database connection error.";
    }else if($result=="MISSING_CLASS"){
        $resultString="Insertion failed.<br/> <b>The first line of the file must be either BT or MT</b>.<br/>Here BT means B.Tech and MT means M.Tech";
    } else {
        $resultString="Some error occured";
    }
    unset($_SESSION['message']);
}else{
    $resultString="Invalid file type. Accepts only .csv file with valid format.";
}

$_SESSION["queryResult"]=$resultString;
$r=constant("HOST11");
header('Location: '.constant("HOST11").'/Backend/Student/student_result.php');

?>
