<?php

/*
 * This file is generated by S. Das.
 * Do not copy it without permission.
 */
//Contact at: tapan84silchar[at]gmail.com
include '../../../../config/config.php';
$name = $_POST['txtName'];
$roll = $_POST['txtRoll'];
$userNm = $_POST['txtUserName'];
$class = $_POST['radioClass'];
$pass = sha1($_POST['txtPassword']);
$advisor_id=$_POST['comboAdvisor'];

//Forward to login page if not authenticated.
session_start();
if (!isset($_SESSION['admin_user_nm'])) {
    header("Location: " . constant("HOST11") . "/Backend/login.php");
}

if (isset($_POST['txtRoll'])) {
    if (!($con = mysql_connect(constant("HOSTNAME"), constant("USERNAME"), constant("PASS")))) {
        $result = "DBCONNECTION_ERROR";
    } else if (!($select = mysql_select_db(constant("DBNAME"), $con))) {
        $result = "DBCONNECTION_ERROR";
    } else {
        $sql = "Update student SET name='$name',user_nm='$userNm',password='$pass',class='$class',last_modified_by='Master',
                advisor_id='$advisor_id' WHERE roll_number='$roll'";
        mysql_query($sql);
        //$row = mysql_fetch_assoc($result);
        if (mysql_affected_rows() >= 1) {
            $_SESSION['queryResult'] = "Edition Successfull!!";
            header("Location: " . constant("HOST11") . "/Backend/Student/student_result.php");
        } else {
            $_SESSION['queryResult'] = "Edition Failed. Try Again.";
            header("Location: " . constant("HOST11") . "/Backend/Student/student_result.php");
        }
    }
    mysql_close($con);
} else {
    $_SESSION['queryResult'] = "Edition not possible. Some error occured";
    header("Location: " . constant("HOST11") . "/Backend/Student/student_result.php");
}
?>
