<?php

/*
 * This file is generated by S. Das.
 * Do not copy it without permission.
 */

//Contact at: tapan84silchar[at]gmail.com
function getAllRecords($class, $page) {
    $result = getLastDate($class);
    if ($result != "DONE") {
        return "DBCONNECTION_ERROR";
    }
    if (!($con = mysql_connect(constant("HOSTNAME"), constant("USERNAME"), constant("PASS")))) {
        $result = "DBCONNECTION_ERROR";
    } else if (!($select = mysql_select_db(constant("DBNAME"), $con))) {
        $result = "DBCONNECTION_ERROR";
    } else {
        $sql = "SELECT roll_number,name,P.user_nm as user_nm,thesis_title,advisor_name,abstract,P.submitted_at as submitted_at
                FROM student as S,advisor as A,projects as P where S.user_nm=P.user_nm and S.advisor_id=A.advisor_id and S.class='" . $class . "'
                ORDER BY roll_number";
        $rs = mysql_query($sql);
        $flag = FALSE;
        $counter = 0;
        $fullClassName = "M.Tech";
        if ($class == "BT") {
            $fullClassName = "B.Tech";
        }
        $inerhtml = '<div style="text-align: center;color: #990000;font-size: 18px;font-weight: bold">' . $fullClassName . ' Thesis Submission List<div>';
        $inerhtml.= '<table border="0" align="center" style="height: 100%; width: 100%">';


        $num_rows = mysql_num_rows($rs);
        $totalPage = ceil($num_rows / 5);
        $paginationHTML = "|";
        for ($i = 1; $i <= $totalPage; $i++) {
            if ($i == $page) {
                $paginationHTML.='&nbsp;&nbsp;&nbsp;<a style="color: red" href="' . constant("HOST11") . '/Backend/Records/record_home.php?class=' . $class . '&pageCount=' . $i . '"><b>' . $i . '</b></a>&nbsp;&nbsp;&nbsp;|';
            } else {
                $paginationHTML.='&nbsp;&nbsp;&nbsp;<a style="color: blue" href="' . constant("HOST11") . '/Backend/Records/record_home.php?class=' . $class . '&pageCount=' . $i . '"><b>' . $i . '</b></a>&nbsp;&nbsp;&nbsp;|';
            }
        }
        $inerhtml.='<tr><td><div style="text-align: center;">' . $paginationHTML . '</td></tr>';


        $startIndex = 1;
        if ($page != 1) {
            $startIndex = (($page - 1) * 5) + 1;
        }
        $counter = 0;
        $lineCounter = 0;


        while ($row = mysql_fetch_assoc($rs)) {
            $counter++;
            if ($counter < $startIndex) {
                continue;
            }
            $flag = TRUE;
            //$lineCounter++;
            if ($class == "BT") {
                $fullClass = "B.Tech";
            } else {
                $fullClass = "M.Tech";
            }
            $isLate = "NO";
            $r = $_SESSION['admin_last_date'];
            $r1 = strtotime($row["submitted_at"]);
            if ($_SESSION['admin_last_date'] < convertMySQLDateIntoPHPTime($row["submitted_at"])) {
                $isLate = "YES";
            }
            $inerhtml.='<tr><td>
                       <table>
                          <tr>
                             <td><div style="text-align: center;color: #006600;font-family: Verdana,Arial,Helvetica,sans-serif;font-size: 18px;">' . stripslashes($row["thesis_title"]) . '</div><td>
                          </tr>
                          <tr>
                            <td>
                              <div style="text-align: left;float: left;color: black;font-family: Verdana,Arial,Helvetica,sans-serif;font-size: 14px;width: 300px;">
                                 <table>
                                 <tr>
                                   <td style="width:40%;color:green">Name:</td>
                                   <td>' . $row["name"] . '</td>
                                 </tr>
                                 <tr>
                                   <td style="width:40%;color:green">Roll:</td>
                                   <td>' . $row["roll_number"] . '</td>
                                 </tr>
                                 <tr>
                                   <td style="width:40%;color:green">Advisor:</td>
                                   <td>' . $row["advisor_name"] . '</td>
                                 </tr>
                                 <tr>
                                   <td style="width:40%;color:green">Submitted at:</td>
                                   <td>' . date("d-F-Y H:i:s", convertMySQLDateIntoPHPTime($row['submitted_at'])) . '</td>
                                 </tr>
                                 <tr>
                                   <td style="width:40%;color:green">Is Late?:</td>
                                   <td>' . $isLate . '</td>
                                 </tr>
                                 <tr>
                                   <td style="width:50%;color:green">Uploaded File:</td>
                                   <td><a href="' . constant("HOST11") . '/GetThesisPDF.php?fn=' . $row["roll_number"] . '-' . $class . 'PI.pdf&cls=' . $class . '">' . $row["roll_number"] . '-' . $class . 'PI.pdf</a></td>
                                 </tr>
                                 </table>
                              </div>
                              <div style="text-align: justify;color: black;font-family: Verdana,Arial,Helvetica,sans-serif;font-size: 14px;">' . stripslashes($row["abstract"]) . '
                              </div>
                            </td>
                          </tr>
                       </table>
                       </td>
                       </tr>';
            $inerhtml = $inerhtml . '<tr><td style="height:2px;background-color: gray"></td></tr>';
            if ($counter >= $startIndex + 4) {
                break;
            }
        }
        $inerhtml.='<tr><td><div style="text-align: center;">' . $paginationHTML . '</td></tr>';
        $inerhtml = $inerhtml . '</table>';
        if ($flag == TRUE) {
            $result = "DONE";
            if(!isset($_SESSION['admin_user_nm'])&&!isset($_SESSION['user_nm'])&&!isset($_SESSION['faculty_user_nm']))
                session_start();
            $_SESSION['innerHTMLSimple'] = $inerhtml;
        } else {
            $result = "NOT_FOUND";
        }
    }
    mysql_close($con);
    return $result;
}


function getAllUploadHistory($class) {
    $result;
    if (!($con = mysql_connect(constant("HOSTNAME"), constant("USERNAME"), constant("PASS")))) {
        $result = "DBCONNECTION_ERROR";
    } else if (!($select = mysql_select_db(constant("DBNAME"), $con))) {
        $result = "DBCONNECTION_ERROR";
    } else {
        $sql = 'select L.user_nm as user_nm,name,roll_number,count(id) as total_upload
                from project_log as L, student as S 
                where L.user_nm=S.user_nm and class="' . $class . '"
                group by L.user_nm 
                order by total_upload desc';
        $result = mysql_query($sql);
        $flag = FALSE;
        $counter = 0;
        $inerhtml = ' <table border="0" align="center" style="height: 100%; width: 100%">
                       <tr>
                                <td style="width: 10px;color: #990000">S.N.</td>
                                <td style="width: 200px;text-align: center;color: #990000">User Name</td>
                                <td style="width: 250px;text-align: center;color: #990000">Name</td>
                                <td style="width: 80px; text-align: center;color: #990000">Roll</td>
                                <td style="width: 150px;text-align: center;color: #990000"># Thesis Uploaded</td>
                            </tr>';
        while ($row = mysql_fetch_assoc($result)) {
            $flag = TRUE;
            $counter++;

            $inerhtml = $inerhtml . '<tr style="background-color: menu;color: black">';
            $inerhtml = $inerhtml . '<td style="width: 10px" align="center">' . $counter . '</td>';
            $inerhtml = $inerhtml . '<td style="width: 200px" align="center"><a href="' . constant("HOST11") . '/Backend/Records/indivisual_upload_history.php?roll=' . $row['roll_number'] . '&user=' . $row["user_nm"] . '&name=' . $row["name"] . '">' . $row['user_nm'] . '</a></td>';
            $inerhtml = $inerhtml . '<td style="width: 250px" align="center">' . $row["name"] . '</td>';
            $inerhtml = $inerhtml . '<td style="width: 80px" align="center">' . $row['roll_number'] . '</td>';
            $inerhtml = $inerhtml . '<td style="width: 150px" align="center">' . $row["total_upload"] . ' Times</td>';
            $inerhtml = $inerhtml . '</tr>';
            $inerhtml = $inerhtml . '<tr><td colspan="6" style="height:2px;background-color: gray"></td></tr>';
        }
        $inerhtml = $inerhtml . '</table>';
        if ($flag == TRUE) {
            $result = "DONE";
            if(!isset($_SESSION['admin_user_nm'])&&!isset($_SESSION['user_nm'])&&!isset($_SESSION['faculty_user_nm']))
                session_start();
            $_SESSION['innerHTMLSimple'] = $inerhtml;
        } else {
            $result = "NOT_FOUND";
        }
    }
    mysql_close($con);
    return $result;
}

function getAllIndivisualUploadHistory($user_nm, $roll, $name) {
    $result;
    if (!($con = mysql_connect(constant("HOSTNAME"), constant("USERNAME"), constant("PASS")))) {
        $result = "DBCONNECTION_ERROR";
    } else if (!($select = mysql_select_db(constant("DBNAME"), $con))) {
        $result = "DBCONNECTION_ERROR";
    } else {
        $sql = 'select uploaded_file_name,submitted_at,submitted_by
                from project_log  where user_nm="' . $user_nm . '" order by submitted_at desc';
        $result = mysql_query($sql);
        $flag = FALSE;
        $counter = 0;
        $inerhtml = '<div style="text-align: center;padding-top: 10px;font-family: Verdana,Arial,Helvetica,sans-serif;">
                     <span style="color: #990000;font-size: 20px">Total Upload History For</span>
                     <br/><span style="color: #009933;font-size: 18px">' . $name . ' , ' . $roll . '</span>
                   </div>';
        $inerhtml.= ' <table border="0" align="center" style="height: 100%; width: 100%">
                       <tr>
                                <td style="width: 10px;color: #990000">S.N.</td>
                                <td style="width: 250px;text-align: center;color: #990000">Submission Date </td>
                                <td style="width: 250px; text-align: center;color: #990000">Uploaded File Name</td>
                                <td style="width: 200px;text-align: center;color: #990000">Uploaded By</td>
                            </tr>';
        while ($row = mysql_fetch_assoc($result)) {
            $flag = TRUE;
            $counter++;

            $inerhtml = $inerhtml . '<tr style="background-color: menu;color: black">';
            $inerhtml = $inerhtml . '<td style="width: 10px" align="center">' . $counter . '</td>';
            $inerhtml = $inerhtml . '<td style="width: 250px" align="center">' . date("d-F-Y H:i", strtotime($row["submitted_at"])) . '</td>';
            $inerhtml = $inerhtml . '<td style="width: 250px" align="center">' . $row["uploaded_file_name"] . '</td>';
            $inerhtml = $inerhtml . '<td style="width: 200px" align="center">' . $row["submitted_by"] . '</td>';
            $inerhtml = $inerhtml . '</tr>';
            $inerhtml = $inerhtml . '<tr><td colspan="6" style="height:2px;background-color: gray"></td></tr>';
        }
        $inerhtml = $inerhtml . '</table>';
        if ($flag == TRUE) {
            $result = "DONE";
            if(!isset($_SESSION['admin_user_nm'])&&!isset($_SESSION['user_nm'])&&!isset($_SESSION['faculty_user_nm']))
                session_start();
            $_SESSION['innerHTMLSimple'] = $inerhtml;
        } else {
            $result = "NOT_FOUND";
        }
    }
    mysql_close($con);
    return $result;
}
function getAllRecordss($class, $page, $option, $text) {
    $result = getLastDate($class);
    if ($result != "DONE") {
        return "DBCONNECTION_ERROR";
    }
    if (!($con = mysql_connect(constant("HOSTNAME"), constant("USERNAME"), constant("PASS")))) {
        $result = "DBCONNECTION_ERROR";
    } else if (!($select = mysql_select_db(constant("DBNAME"), $con))) {
        $result = "DBCONNECTION_ERROR";
    } else {
              $sql="";
           if($option!="")
           { 
                $first="";
                
                if($option=="Roll")
                $first="roll_number";
                else if($option=="Name")
                $first="name";
                else if($option=="Advisor")
                $first="advisor_name";
                else if($option=="thesis")
                $first="abstract";
                else
                $first="thesis_title";
                
            $sql = "SELECT roll_number,name,P.user_nm as user_nm,thesis_title,advisor_name,abstract,P.submitted_at as submitted_at
                FROM student as S,advisor as A,projects as P where S.user_nm=P.user_nm and S.advisor_id=A.advisor_id and S.class='" . $class . "' AND ".$first." LIKE '%".$text."%'
                ORDER BY roll_number";
          }
          else
          {
            $sql = "SELECT roll_number,name,P.user_nm as user_nm,thesis_title,advisor_name,abstract,P.submitted_at as submitted_at
                FROM student as S,advisor as A,projects as P where S.user_nm=P.user_nm and S.advisor_id=A.advisor_id and S.class='" . $class . "'
                ORDER BY roll_number";
          
          }
		 // echo $sql;
        $rs = mysql_query($sql);
        $flag = FALSE;
        $counter = 0;
        $fullClassName = "M.Tech";
        if ($class == "BT") {
            $fullClassName = "B.Tech";
        }
        $inerhtml = '<div style="text-align: center;color: #990000;font-size: 18px;font-weight: bold">' . $fullClassName . ' Thesis Submission List<div>';
        $inerhtml.= '<table border="0" align="center" style="height: 100%; width: 100%">';


        $num_rows = mysql_num_rows($rs);
        $totalPage = ceil($num_rows / 5);
        $paginationHTML = "|";
        for ($i = 1; $i <= $totalPage; $i++) {
            if ($i == $page) {
                $paginationHTML.='&nbsp;&nbsp;&nbsp;<a style="color: red" href="' . constant("HOST11") . '/Backend/Records/record_home.php?class=' . $class . '&pageCount=' . $i . '"><b>' . $i . '</b></a>&nbsp;&nbsp;&nbsp;|';
            } else {
                $paginationHTML.='&nbsp;&nbsp;&nbsp;<a style="color: blue" href="' . constant("HOST11") . '/Backend/Records/record_home.php?class=' . $class . '&pageCount=' . $i . '"><b>' . $i . '</b></a>&nbsp;&nbsp;&nbsp;|';
            }
        }
        $inerhtml.='<tr><td><div style="text-align: center;">' . $paginationHTML . '</td></tr>';


        $startIndex = 1;
        if ($page != 1) {
            $startIndex = (($page - 1) * 5) + 1;
        }
        $counter = 0;
        $lineCounter = 0;


        while ($row = mysql_fetch_assoc($rs)) {
            $counter++;
            if ($counter < $startIndex) {
                continue;
            }
            $flag = TRUE;
            //$lineCounter++;
            if ($class == "BT") {
                $fullClass = "B.Tech";
            } else {
                $fullClass = "M.Tech";
            }
            $isLate = "NO";
            $r = $_SESSION['admin_last_date'];
            $r1 = strtotime($row["submitted_at"]);
            if ($_SESSION['admin_last_date'] < convertMySQLDateIntoPHPTime($row["submitted_at"])) {
                $isLate = "YES";
            }
            $inerhtml.='<tr><td>
                       <table>
                          <tr>
                             <td><div style="text-align: center;color: #006600;font-family: Verdana,Arial,Helvetica,sans-serif;font-size: 18px;">' . stripslashes($row["thesis_title"]) . '</div><td>
                          </tr>
                          <tr>
                            <td>
                              <div style="text-align: left;float: left;color: black;font-family: Verdana,Arial,Helvetica,sans-serif;font-size: 14px;width: 300px;">
                                 <table>
                                 <tr>
                                   <td style="width:40%;color:green">Name:</td>
                                   <td>' . $row["name"] . '</td>
                                 </tr>
                                 <tr>
                                   <td style="width:40%;color:green">Roll:</td>
                                   <td>' . $row["roll_number"] . '</td>
                                 </tr>
                                 <tr>
                                   <td style="width:40%;color:green">Advisor:</td>
                                   <td>' . $row["advisor_name"] . '</td>
                                 </tr>
                                 <tr>
                                   <td style="width:40%;color:green">Submitted at:</td>
                                   <td>' . date("d-F-Y H:i:s", convertMySQLDateIntoPHPTime($row['submitted_at'])) . '</td>
                                 </tr>
                                 <tr>
                                   <td style="width:40%;color:green">Is Late?:</td>
                                   <td>' . $isLate . '</td>
                                 </tr>
                                 <tr>
                                   <td style="width:50%;color:green">Uploaded File:</td>
                                   <td><a href="' . constant("HOST11") . '/GetThesisPDF.php?fn=' . $row["roll_number"] . '-' . $class . 'PI.pdf&cls=' . $class . '">' . $row["roll_number"] . '-' . $class . 'PI.pdf</a></td>
                                 </tr>
                                 </table>
                              </div>
                              <div style="text-align: justify;color: black;font-family: Verdana,Arial,Helvetica,sans-serif;font-size: 14px;">' . stripslashes($row["abstract"]) . '
                              </div>
                            </td>
                          </tr>
                       </table>
                       </td>
                       </tr>';
            $inerhtml = $inerhtml . '<tr><td style="height:2px;background-color: gray"></td></tr>';
            if ($counter >= $startIndex + 4) {
                break;
            }
        }
        $inerhtml.='<tr><td><div style="text-align: center;">' . $paginationHTML . '</td></tr>';
        $inerhtml = $inerhtml . '</table>';
        if ($flag == TRUE) {
            $result = "DONE";
            //session_start();
            $_SESSION['innerHTMLSimple'] = $inerhtml;
        } else {
            $result = "NOT_FOUND";
        }
    }
    mysql_close($con);
    return $result;
}
function getAllUploadHistorys($class,$name) {
    $result;
    if (!($con = mysql_connect(constant("HOSTNAME"), constant("USERNAME"), constant("PASS")))) {
        $result = "DBCONNECTION_ERROR";
    } else if (!($select = mysql_select_db(constant("DBNAME"), $con))) {
        $result = "DBCONNECTION_ERROR";
    } else {
        $sql="";
        if($name=="")
        { $sql = 'select L.user_nm as user_nm,name,roll_number,count(id) as total_upload
                from project_log as L, student as S 
                where L.user_nm=S.user_nm and class="' . $class . '"
                group by L.user_nm 
                order by total_upload desc';
                }
        else
        { $sql = 'select L.user_nm as user_nm,name,roll_number,count(id) as total_upload
                from project_log as L, student as S 
                where L.user_nm=S.user_nm and class="' . $class . '" AND name LIKE "%'.$name.'%"
                group by L.user_nm 
                order by total_upload desc';
                }

        echo $sql;
        $result = mysql_query($sql);
        $flag = FALSE;
        $counter = 0;
        $inerhtml = ' <table border="0" align="center" style="height: 100%; width: 100%">
                       <tr>
                                <td style="width: 10px;color: #990000">S.N.</td>
                                <td style="width: 200px;text-align: center;color: #990000">User Name</td>
                                <td style="width: 250px;text-align: center;color: #990000">Name</td>
                                <td style="width: 80px; text-align: center;color: #990000">Roll</td>
                                <td style="width: 150px;text-align: center;color: #990000"># Thesis Uploaded</td>
                            </tr>';
        while ($row = mysql_fetch_assoc($result)) {
            $flag = TRUE;
            $counter++;

            $inerhtml = $inerhtml . '<tr style="background-color: menu;color: black">';
            $inerhtml = $inerhtml . '<td style="width: 10px" align="center">' . $counter . '</td>';
            $inerhtml = $inerhtml . '<td style="width: 200px" align="center"><a href="' . constant("HOST11") . '/Backend/Records/indivisual_upload_history.php?roll=' . $row["roll_number"] . '&user=' . $row["user_nm"] . '&name=' . $row["name"] . '">' . $row["user_nm"] . '</a></td>';
            $inerhtml = $inerhtml . '<td style="width: 250px" align="center">' . $row["name"] . '</td>';
            $inerhtml = $inerhtml . '<td style="width: 80px" align="center">' . $row["roll_number"] . '</td>';
            $inerhtml = $inerhtml . '<td style="width: 150px" align="center">' . $row["total_upload"] . ' Times</td>';
            $inerhtml = $inerhtml . '</tr>';
            $inerhtml = $inerhtml . '<tr><td colspan="6" style="height:2px;background-color: gray"></td></tr>';
        }
        $inerhtml = $inerhtml . '</table>';
        if ($flag == TRUE) {
            $result = "DONE";
            //session_start();
            $_SESSION['innerHTMLSimple'] = $inerhtml;
        } else {
            $result = "NOT_FOUND";
        }
    }
    mysql_close($con);
    return $result;
}
?>
