/* 
 * This file is generated by S. Das.
 * Do not copy it without permission.
 */
function getPermission(user_nm,faculty_id,targetID){
    var xmlhttp;
    if (1!=1)
    {
        document.getElementById(targetID).innerHTML="Error!!! Invalid argument passed.";
        return;
    }
    if (window.XMLHttpRequest)
    {// code for IE7+, Firefox, Chrome, Opera, Safari
        xmlhttp=new XMLHttpRequest();
    }
    else
    {// code for IE6, IE5
        xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
    }
    var url = "PhpIncludeFiles/form_submit/grant_permission.php";
    var params = "user_nm="+user_nm+"&faculty_id="+faculty_id;
    //alert(params);
    //alert(url);
    xmlhttp.open("POST", url, true);
    //Send the proper header information along with the request
    xmlhttp.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
    xmlhttp.setRequestHeader("Content-length", params.length);
    xmlhttp.setRequestHeader("Connection", "close");
    
    xmlhttp.onreadystatechange=function()
    {
        if (xmlhttp.readyState==4 && xmlhttp.status==200)
        {
            document.getElementById(targetID).innerHTML=xmlhttp.responseText;
        }
    }
    xmlhttp.send(params);
}

