<?php

/*
 * This file is generated by S. Das.
 * Do not copy it without permission.
 */
//Contact at: tapan84silchar[at]gmail.com
// output headers so that the file is downloaded rather than displayed
header('Content-Type: text/csv; charset=utf-8');
include '../../config/config.php';
include '../PhpIncludeFiles/CommonFunctions.php';

//Forward to login page if not authenticated.
session_start();
if (!isset($_SESSION['admin_user_nm'])) {
    header("Location: " . constant("HOST11") . "/Backend/login.php");
}


$format = "NONE";
$roll = "MT";
if (isset($_GET['csv'])) {
    $format = $_GET['csv'];
    if ($format != "SF" && $format != "PF" && $format != "AF") {
        $format = "NONE";
    }
    $roll = $_GET['class'];
    if ($roll != "BT" && $roll != "MT") {
        $roll = "NONE";
    }
}
$fileName = "";
$result;
if ($format == "SF") {
    $fileName = "StudentInformation_" . date('d-F') . ".csv";
    // create a file pointer connected to the output stream
    header('Content-Disposition: attachment; filename=' . $fileName);
    $output = fopen('php://output', 'w');

    if (!($con = mysql_connect(constant("HOSTNAME"), constant("USERNAME"), constant("PASS")))) {
        $result = "DBCONNECTION_ERROR";
    } else if (!($select = mysql_select_db(constant("DBNAME"), $con))) {
        $result = "DBCONNECTION_ERROR";
    } else {
        $sql = "select roll_number,name,user_nm,class,password from student where pass_changed='NO' and class='" . $roll . "'";
        $rs = mysql_query($sql);
        //$num_rows = mysql_num_rows($rs);
        while ($row = mysql_fetch_assoc($rs)) {
            $data[0] = $row['roll_number'] . ',' . $row['name'] . ',' . $row['user_nm'] . ',' . $row['class'] . ',' . $row['password'];
            fputcsv($output, $data, ',', '"');
        }
    }
} else if ($format == "AF") {
    $fileName = "Info_For_Advisor_" . date('d-F') . ".csv";
    header('Content-Disposition: attachment; filename=' . $fileName);
    $output = fopen('php://output', 'w');

    if (!($con = mysql_connect(constant("HOSTNAME"), constant("USERNAME"), constant("PASS")))) {
        $result = "DBCONNECTION_ERROR";
    } else if (!($select = mysql_select_db(constant("DBNAME"), $con))) {
        $result = "DBCONNECTION_ERROR";
    } else {
        $sql = "select roll_number,name,S.user_nm as user_nm,class,password from student where pass_changed='NO'and class='" . $roll . "'";
        $rs = mysql_query($sql);
        //$num_rows = mysql_num_rows($rs);
        while ($row = mysql_fetch_assoc($rs)) {
            $data[0] = $row['roll_number'] . ',' . $row['name'] . ',' . $row['user_nm'] . ',' . $row['class'] . ',' . $row['password'];
            fputcsv($output, $data, ',', '"');
        }
    }
} else if ($format == "PF") {
    $fileName = "ThesisInformation_" . date('d-F') . ".csv";
    header('Content-Disposition: attachment; filename=' . $fileName);
    $output = fopen('php://output', 'w');
    getLastDate($roll);
    if (!($con = mysql_connect(constant("HOSTNAME"), constant("USERNAME"), constant("PASS")))) {
        $result = "DBCONNECTION_ERROR";
    } else if (!($select = mysql_select_db(constant("DBNAME"), $con))) {
        $result = "DBCONNECTION_ERROR";
    } else {
        $sql = "select roll_number,name,S.user_nm as user_nm,class,thesis_title,advisor_name,P.advisor_id as advisor_id,submitted_at,advisor_permission
                FROM student as S, projects as P, advisor as A
                WHERE S.user_nm=P.user_nm and P.advisor_id=A.advisor_id and S.class='" . $roll . "'";
        $rs = mysql_query($sql);
        while ($row = mysql_fetch_assoc($rs)) {
            $unix_submitted_at = convertMySQLDateIntoPHPTime($row['submitted_at']);
            if ($_SESSION['admin_last_date']< $unix_submitted_at) {
                $late_submission = "YES";
            } else {
                $late_submission = "NO";
            }
            $thesisLink=  constant("HOST11").'/web/Upload/'.$row['class'].'/'.$row['roll_number'].'-'.$row['class'].'PI.pdf';
            $data[0] = $row['roll_number'] . ',' . $row['name'] . ',' . $row['user_nm'] . ',' . $row['class'] . ',' . $row['thesis_title'] . ',' . $row['advisor_name'] .',' . $row['advisor_id'] . ',' . $thesisLink .',' . date("d-M-Y", $unix_submitted_at) . ',' . $late_submission.','.$row['advisor_permission'];
            fputcsv($output, $data, ',', '"');
        }
    }
}

//if ($result == "DONE") {
//    echo 'task done';
//}
?>
