<?php

/*
 * This file is generated by S. Das.
 * Do not copy it without permission.
 */

//Contact at: tapan84silchar[at]gmail.com
function getAllStudents($class, $advisor) {
    $result="NONE";
    if (!($con = mysql_connect(constant("HOSTNAME"), constant("USERNAME"), constant("PASS")))) {
        $result = "DBCONNECTION_ERROR";
    } else if (!($select = mysql_select_db(constant("DBNAME"), $con))) {
        $result = "DBCONNECTION_ERROR";
    } else {
        $sql = "SELECT name,roll_number,S.user_nm as user_nm,permission,IFNULL( report_file_name, 'Not Uploaded' ) AS report_file_name FROM student as S LEFT OUTER JOIN projects as P ON S.user_nm=P.user_nm  WHERE class='" . $class . "' AND advisor_id='" . $advisor . "'";
        $sql_result = mysql_query($sql);
        $flag = FALSE;
        $counter = 0;
        $inerhtml = '';
        while ($row = mysql_fetch_assoc($sql_result)) {
            $flag = TRUE;
            $counter++;
            if ($class == "BT") {
                $fullClass = "B.Tech";
            } else {
                $fullClass = "M.Tech";
            }
//<a href="'.constant("HOST11").'/GetThesisPDF.php?fn='.$row["roll_number"].'-'.$row['class'].'PI.pdf&cls='.$row["class"].'">'.$row["roll_number"].'-'.$row['class'].'PI.pdf</a>
            /*             * ********************************************** */
            //Get the total number of permission granted.
//            $sql_inner_result = mysql_query("");
//            while ($row = mysql_fetch_array($sql_inner_result)) {
//                $total_permission = $row[0];
//            }
            /*             * ********************************************** */
            if($row["permission"]=="YES"){
                $permission_string='<span style="color: green">Permission currently granted.</span>';
            }else{
                $permission_string='<span style="color: red">Permission currently disabled.</span>';
            }
            
            $thesisLinkString="Not Uploaded";
            if($row["report_file_name"]!="Not Uploaded"){
                $thesisLinkString='<a href="'.constant("HOST11").'/GetThesisPDF.php?fn='.$row["roll_number"].'-'.$class.'PI.pdf&cls='.$class.'">Click Here</a>';
            }
            
			$plaigiarismLinkString='<a href="'.constant("HOST11").'/Upload/'.$class.'/Report/'.$row["roll_number"].'-'.$class.'PI/summary.html" target="_blank">View</a>';
            
            if ($counter % 2 == 0) {
                $inerhtml = $inerhtml . '<div id="ListEvenRow">';
            } else {
                $inerhtml = $inerhtml . '<div id="ListOddRow">';
            }
            $inerhtml = $inerhtml . '<div id="TSrlNoValue">' . $counter . '</div>';
            $inerhtml = $inerhtml . '<div id="RollNoValue">
                                       <a href="'.constant("HOST11").'/faculty/PhpIncludeFiles/GetPermissionHistory.php?user_nm='.$row['user_nm'].'" onclick="window.open(\''.constant("HOST11").'/faculty/PhpIncludeFiles/GetPermissionHistory.php?user_nm='.$row["user_nm"].'\',\'popup\',\'width=500,height=500,scrollbars=no,resizable=no,toolbar=no,directories=no,location=no,menubar=no,status=no,left=0,top=0\'); return false">'.$row['roll_number'].'</a></div>';
            $inerhtml = $inerhtml . '<div id="NameValue">' . $row["name"] . '</div>';
            $inerhtml = $inerhtml . '<div id="ThesisLinkValue">' . $thesisLinkString . '</div>';
            $inerhtml = $inerhtml . '<div id="PermissionValue"><input type="button" 
                                     value="Grant Permission" name="permission" 
                                     onclick="getPermission(\''.$row["user_nm"].'\',\''.$_SESSION["faculty_user_nm"].'\',\'StatusValue'.$class.'_'.$counter.'\')"/></div>';
			$inerhtml = $inerhtml . '<div id="Plaigiarism">' . $plaigiarismLinkString . '</div>';
            $inerhtml = $inerhtml . '<div id="StatusValue'.$class.'_'.$counter.'" style="StatusValue">'.$permission_string.'</div>';
            $inerhtml = $inerhtml . '</div>';
        }
        if ($flag == TRUE) {
            $result = "DONE";
            if(!isset($_SESSION['user_nm'])&&!isset($_SESSION['admin_user_nm'])&&!isset($_SESSION['faculty_user_nm']))
                session_start();
            $_SESSION['innerHTMLSimple'] = $inerhtml;
        } else {
            $result = "NOT_FOUND";
        }
    }
    mysql_close($con);
    return $result;
}


function grant_permission($user_nm,$faculty_id){
    $result="NONE";
    if (!($con = mysql_connect(constant("HOSTNAME"), constant("USERNAME"), constant("PASS")))) {
        $result = "DBCONNECTION_ERROR";
    } else if (!($select = mysql_select_db(constant("DBNAME"), $con))) {
        $result = "DBCONNECTION_ERROR";
    } else {
        $sql = "UPDATE student set permission='YES',last_modified_by='$faculty_id' where user_nm='$user_nm'";
        $sql_result = mysql_query($sql);
        if (mysql_affected_rows() >= 1) {
            $result = "DONE";
        } else {
            $result = "NOT_FOUND";
        }
    }
    mysql_close($con);
    return $result;
}

function changePasswd($faculty_id,$pass, $pass1) {
    $result="NONE";
    if ((!preg_match(getPasswordPattern(), $pass))
            || (!preg_match(getPasswordPattern(), $pass1))) {
        $result = "INVALID";
    } else if (!($con = mysql_connect(constant("HOSTNAME"), constant("USERNAME"), constant("PASS")))) {
        $result = "DBCONNECTION_ERROR";
    } else if (!($select = mysql_select_db(constant("DBNAME"), $con))) {
        $result = "DBCONNECTION_ERROR";
    } else {
        $pass1 = sha1($pass1);
        $sql = "UPDATE advisor SET pass='$pass1',last_modified_at='".date( 'Y-m-d H:i:s')."' WHERE advisor_id='$faculty_id'";
        $sql_result = mysql_query($sql);
        if (mysql_affected_rows() >= 1) {
            $result = "DONE";
        } else {
            $result = "DB_ERROR";
        }
    }
    mysql_close($con);
    return $result;
}

function getAllUploadHistory($stud_id){
    $result="NONE";
    if (!($con = mysql_connect(constant("HOSTNAME"), constant("USERNAME"), constant("PASS")))) {
        $result = "DBCONNECTION_ERROR";
    } else if (!($select = mysql_select_db(constant("DBNAME"), $con))) {
        $result = "DBCONNECTION_ERROR";
    } else {
        //Get student name........
        $sql = "select name from student where user_nm='".$stud_id."'";
        $sql_result1 = mysql_query($sql);
        $student_name="NONE";
        while ($row = mysql_fetch_assoc($sql_result1)) {
            $student_name=$row["name"];
        }
        if($student_name=="NONE"){
            return "STUDENT_NOT_FOUND";
        }else{
            if(!isset($_SESSION['user_nm'])&&!isset($_SESSION['admin_user_nm'])&&!isset($_SESSION['faculty_user_nm']))
                session_start();
            $_SESSION['student_name']=$student_name;
        }
        
        //Get his history.......
        $sql = "select advisor_name,permitted_at from permission_log as P,advisor as A where P.advisor_id=A.advisor_id and P.permitted_to='".$stud_id."' ORDER BY permitted_at";
        $sql_result = mysql_query($sql);
        $flag = FALSE;
        $counter = 0;
        $inerhtml = '';
        while ($row = mysql_fetch_assoc($sql_result)) {
            $flag = TRUE;
            $counter++;
            $phpdate=  strtotime($row["permitted_at"]);                        
            if ($counter % 2 == 0) {
                $inerhtml = $inerhtml . '<tr style="text-align: center;width: 480px;background-color: #ffffff;color: black;font-weight: normal">';
            } else {
                $inerhtml = $inerhtml . '<tr style="text-align: center;width: 480px;background-color: #cccccc;color: black;font-weight: normal">';
            }
            $inerhtml = $inerhtml . '<td style="width: 50px">' . $counter . '</td>';
            $inerhtml = $inerhtml . ' <td style="width: 100px">'.date('d-M-Y',$phpdate).'</td>';
            $inerhtml = $inerhtml . '<td style="width: 80px">'.date('H:i',$phpdate).'</td>';
            $inerhtml = $inerhtml . '<td style="width: 250px">'.$row["advisor_name"].'</td>';
        }
        if ($flag == TRUE) {
            $result = "DONE";
            $_SESSION['innerHTMLSimple'] = $inerhtml;
        } else {
            $result = "NO_HISTORY_FOUND";
        }
    }
    mysql_close($con);
    return $result;
}

?>
