<?php

/*
 * This file is generated by S. Das.
 * Do not copy it without permission.
 */
//Contact at: tapan84silchar[at]gmail.com
//include '../config/config.php';

function getAllAdvisors() {
    $result;
    if (!($con = mysql_connect(constant("HOSTNAME"), constant("USERNAME"), constant("PASS")))) {
        $result = "DBCONNECTION_ERROR";
    } else if (!($select = mysql_select_db(constant("DBNAME"), $con))) {
        $result = "DBCONNECTION_ERROR";
    } else {
        $sql = "SELECT advisor_name,advisor_id from advisor";
        $result = mysql_query($sql);
        $flag = FALSE;
        $counter = 0;
        $inerhtml = '<select name="comboAdvisor"><option value="NONE">Select</option>';
        while ($row = mysql_fetch_assoc($result)) {
            $flag = TRUE;
            $inerhtml = $inerhtml . '<option value="' . $row['advisor_id'] . '">' . $row['advisor_name'] . '</option>';
        }
        $inerhtml = $inerhtml . '</select>';
        if ($flag == TRUE) {
            $result = "DONE";
            session_start();
            $_SESSION['advisor_list'] = $inerhtml;
        } else {
            $result = "NOT_FOUND";
        }
    }
    mysql_close($con);
    return $result;
}

function getLastDate($class) {
    $result;
    if (!($con = mysql_connect(constant("HOSTNAME"), constant("USERNAME"), constant("PASS")))) {
        $result = "DBCONNECTION_ERROR";
    } else if (!($select = mysql_select_db(constant("DBNAME"), $con))) {
        $result = "DBCONNECTION_ERROR";
    } else {
        $sql = "SELECT last_date from schedule where class='" . $class . "'";
        $result = mysql_query($sql);
        $flag = FALSE;
        while ($row = mysql_fetch_assoc($result)) {
            $flag = TRUE;
            if(!isset($_SESSION['admin_user_nm'])&&!isset($_SESSION['user_nm'])&&!isset($_SESSION['faculty_user_nm']))
                session_start();
            $_SESSION['last_date'] =convertMySQLDateIntoPHPTime($row['last_date']." 18:00:00");
        }
        if ($flag == TRUE) {
            $result = "DONE";
        } else {
            $result = "NOT_FOUND";
        }
    }
    mysql_close($con);
    return $result;
}

//function getPermission($stud_id){
//    $result="NONE";
//    if (!($con = mysql_connect(constant("HOSTNAME"), constant("USERNAME"), constant("PASS")))) {
//        $result = "DBCONNECTION_ERROR";
//    } else if (!($select = mysql_select_db(constant("DBNAME"), $con))) {
//        $result = "DBCONNECTION_ERROR";
//    } else {
//        $sql = "SELECT permission from schedule where class='" . $class . "'";
//        $result = mysql_query($sql);
//        $flag = FALSE;
//        while ($row = mysql_fetch_assoc($result)) {
//            $flag = TRUE;
//            session_start();
//            $_SESSION['last_date'] =convertMySQLDateIntoPHPTime($row['last_date']." 18:00:00");
//        }
//        if ($flag == TRUE) {
//            $result = "DONE";
//        } else {
//            $result = "NOT_FOUND";
//        }
//    }
//    mysql_close($con);
//    return $result;
//}


function getAllRecords() {
    $result = getLastDate($_SESSION['class']);
    if ($result != "DONE") {
        return "DBCONNECTION_ERROR";
    }
    if (!($con = mysql_connect(constant("HOSTNAME"), constant("USERNAME"), constant("PASS")))) {
        $result = "DBCONNECTION_ERROR";
    } else if (!($select = mysql_select_db(constant("DBNAME"), $con))) {
        $result = "DBCONNECTION_ERROR";
    } else {
        $sql = "SELECT roll_number,name,P.user_nm as user_nm,S.class as class,thesis_title,report_file_name,advisor_name,abstract,P.submitted_at as submitted_at
                FROM student as S,advisor as A,projects as P where S.user_nm=P.user_nm and S.advisor_id=A.advisor_id and S.user_nm='" . $_SESSION['user_nm'] . "'";
        $rs = mysql_query($sql);
        $flag = FALSE;
        $inerhtml = '<table border="0" align="center" style="height: 100%; width: 100%">';
        while ($row = mysql_fetch_assoc($rs)) {
            $flag = TRUE;
            if ($row['class'] == "BT") {
                $fullClass = "B.Tech";
            } else {
                $fullClass = "M.Tech";
            }
            $isLate = "NO";
            if ($_SESSION['last_date'] < convertMySQLDateIntoPHPTime($row["submitted_at"])) {
                $isLate = "YES";
            }
            $inerhtml.='<tr><td>
                       <table>
                          <tr>
                             <td><div style="height: 50px; padding-top: 20px; text-align: center;color: #006600;font-family: Verdana,Arial,Helvetica,sans-serif;font-size: 18px;"><b>' . stripslashes($row["thesis_title"]) . '</b></div><td>
                          </tr>
                          <tr>
                            <td>
                              <div style="padding: 20px; text-align: left;float: left;color: black;font-family: Verdana,Arial,Helvetica,sans-serif;font-size: 14px;width: 350px;">
                                 <table>
                                 <tr>
                                   <td style="width:50%;color:green">Name:</td>
                                   <td>' . $row["name"] . '</td>
                                 </tr>
                                 <tr>
                                   <td style="width:50%;color:green">Roll:</td>
                                   <td>' . $row["roll_number"] . '</td>
                                 </tr>
                                 <tr>
                                   <td style="width:50%;color:green">Advisor:</td>
                                   <td>' . $row["advisor_name"] . '</td>
                                 </tr>
                                 <tr>
                                   <td style="width:50%;color:green">Submitted at:</td>
                                   <td>' . date("d-F-Y H:i:s", convertMySQLDateIntoPHPTime($row['submitted_at'])) . '</td>
                                 </tr>
                                 <tr>
                                   <td style="width:50%;color:green">Is Late?:</td>
                                   <td>' . $isLate . '</td>
                                 </tr>
                                 <tr>
                                   <td style="width:50%;color:green">Uploaded File:</td>
                                   <td><a href="'.constant("HOST11").'/GetThesisPDF.php?fn='.$row["roll_number"].'-'.$row['class'].'PI.pdf&cls='.$row["class"].'">'.$row["roll_number"].'-'.$row['class'].'PI.pdf</a></td>
                                 </tr>
                                 </table>
                              </div>
                              <div style="text-align: justify;color: black;font-family: Verdana,Arial,Helvetica,sans-serif;font-size: 14px;"><b>Abstract: </b>' . stripslashes($row["abstract"]) . '
                              </div>
                            </td>
                          </tr>
                       </table>
                       </td>
                       </tr>';
            $inerhtml = $inerhtml . '<tr><td style="height:2px;background-color: gray"></td></tr>';
        }
        $inerhtml = $inerhtml . '</table>';
        if ($flag == TRUE) {
            $result = "DONE";
            if(!isset($_SESSION['admin_user_nm'])&&!isset($_SESSION['user_nm'])&&!isset($_SESSION['faculty_user_nm']))
                session_start();
            $_SESSION['innerHTMLSimple'] = $inerhtml;
        } else {
            $result = "NOT_FOUND";
        }
    }
    mysql_close($con);
    return $result;
}

?>
