<?php

/*
 * This file is generated by S. Das.
 * Do not copy it without permission.
 */
//Contact at: tapan84silchar[at]gmail.com
include '../config/config.php';
session_start();
unset($_SESSION['faculty_user_nm']);
unset($_SESSION['faculty_name']);
//header("Location: ".constant("HOST11")."/faculty/login.php");
header("Location: ".constant("HOST11")."/login.php");
?>
