<!--
This file is generated by S. Das.
Do not copy it without permission.
-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title></title>
    </head>
    <body>
        <?php
        // put your code here
        $phpdate=  strtotime("2012-4-13 10:31:00");
        echo $phpdate;
        echo '<br></br>';
        echo date('d-M-Y',$phpdate);
        echo '<br></br>';
        echo date('H:i',$phpdate);
        $s="TAPAN1";
        if($s=="TAPAN"){
            echo 'hiii';
        }
        ?>
    </body>
</html>
